USE [master]
GO

/****** Object:  Database [STUDENTDB]    Script Date: 10.02.2023 14:53:38 ******/
CREATE DATABASE [STUDENTDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'STUDENTDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS01\MSSQL\DATA\STUDENTDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'STUDENTDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS01\MSSQL\DATA\STUDENTDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [STUDENTDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [STUDENTDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [STUDENTDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [STUDENTDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [STUDENTDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [STUDENTDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [STUDENTDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [STUDENTDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [STUDENTDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [STUDENTDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [STUDENTDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [STUDENTDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [STUDENTDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [STUDENTDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [STUDENTDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [STUDENTDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [STUDENTDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [STUDENTDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [STUDENTDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [STUDENTDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [STUDENTDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [STUDENTDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [STUDENTDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [STUDENTDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [STUDENTDB] SET  MULTI_USER 
GO

ALTER DATABASE [STUDENTDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [STUDENTDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [STUDENTDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [STUDENTDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [STUDENTDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [STUDENTDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [STUDENTDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [STUDENTDB] SET  READ_WRITE 
GO

